spring:
  application:
    name: "order-service"

  datasource:
    url: "jdbc:postgresql://localhost:5433/order-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibarnate:
        dialect: org.hibarnate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddl-auto: update

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true