spring:
  application:
    name: "discovery-server"

server:
  port: 8761


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: "localhost"
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: false
    fetch-registry: false