spring:
  application:
    name: "product-service"

  data:
    mongodb:
      database: product-service
      port: 27018
      uri: mongodb://localhost:27018/product-service
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true