apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort #k8s service types
  ports:
    - port: 5432 #cluster içindeki postgresql servis portu
      targetPort: 5432 # pod içinde gideceği port
      nodePort: 30007 #30000-32767 arasında olmalı
  selector:
    app: postgres