spring:
  application:
    name: "cart-service"
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: orderCreatedFunction
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderCreatedFunction-in-0:
          destination: order-topic
          content-type: application/json
          group: cart-group

  data:
    mongodb:
      database: cart-service
      port: 27019
      uri: mongodb://localhost:27019

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true