spring:
  application:
    name: "cart-service"
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: orderCreatedFunction
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderCreatedFunction-in-0:
          destination: order-topic
          content-type: application/json
          group: cart-group

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/cart-service?authSource=admin

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true