spring:
  application:
    name: "cart-service"

  data:
    mongodb:
      database: cart-service
      port: 27019
      uri: mongodb://localhost:27019

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true